import 'package:almohsen_s_application13/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:almohsen_s_application13/widgets/custom_elevated_button.dart';import 'widgets/profiledetails_item_widget.dart';import 'models/profiledetails_item_model.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application13/core/app_export.dart';import 'controller/profile_details_controller.dart';class ProfileDetailsScreen extends GetWidget<ProfileDetailsController> {const ProfileDetailsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 30.v), child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgEllipse5, height: 250.adaptSize, width: 250.adaptSize, radius: BorderRadius.circular(125.h)), SizedBox(height: 26.v), Text("lbl_jenny_wilson".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 19.v), CustomElevatedButton(height: 45.v, width: 101.h, text: "lbl_follow".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL22, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700_1, onPressed: () {onTapFollow();}), SizedBox(height: 21.v), Divider(), SizedBox(height: 20.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [GestureDetector(onTap: () {onTapAutoLayoutVertical();}, child: Padding(padding: EdgeInsets.only(bottom: 2.v), child: Column(children: [Text("lbl_9_489".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 8.v), Text("lbl_followers".tr, style: CustomTextStyles.titleMediumGray70001Medium)]))), Padding(padding: EdgeInsets.only(left: 70.h), child: Column(children: [Text("lbl_2_475".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 10.v), Text("lbl_following".tr, style: CustomTextStyles.titleMediumGray70001Medium)]))]), SizedBox(height: 20.v), Divider(), SizedBox(height: 15.v), _buildPlaylists(), SizedBox(height: 13.v), _buildProfileDetails()])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 11.v)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v))]); } 
/// Section Widget
Widget _buildPlaylists() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_playlists".tr, style: theme.textTheme.headlineSmall), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 6.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer16))]); } 
/// Section Widget
Widget _buildProfileDetails() { return SizedBox(height: 248.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: controller.profileDetailsModelObj.value.profiledetailsItemList.value.length, itemBuilder: (context, index) {ProfiledetailsItemModel model = controller.profileDetailsModelObj.value.profiledetailsItemList.value[index]; return ProfiledetailsItemWidget(model);}))); } 
/// Navigates to the songPlayScreen when the action is triggered.
onTapFollow() { Get.toNamed(AppRoutes.songPlayScreen, ); } 

onTapAutoLayoutVertical() { // TODO: implement Actions
 } 
 }
