import 'package:almohsen_s_application13/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_title.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application13/core/app_export.dart';import 'controller/notification_settings_controller.dart';class NotificationSettingsScreen extends GetWidget<NotificationSettingsController> {const NotificationSettingsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 29.v), child: Column(children: [_buildRecommendedMusic(), SizedBox(height: 27.v), _buildNewMusic(), SizedBox(height: 29.v), _buildPlaylistUpdates(), SizedBox(height: 26.v), _buildConcertNotifications(), SizedBox(height: 28.v), _buildArtistUpdates(), SizedBox(height: 26.v), _buildProductNews(), SizedBox(height: 26.v), _buildHearMeOffers(), SizedBox(height: 28.v), _buildNewEpisodes(), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v)), title: AppbarTitle(text: "msg_notification_settings".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildRecommendedMusic() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_recommended_music".tr, style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 7.v), Text("lbl_push_email".tr, style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 13.v))]); } 
/// Section Widget
Widget _buildNewMusic() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_new_music".tr, style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 6.v), Text("lbl_push".tr, style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 12.v))]); } 
/// Section Widget
Widget _buildPlaylistUpdates() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_playlist_updates".tr, style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 5.v), Text("lbl_push_email".tr, style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 11.v, bottom: 13.v))]); } 
/// Section Widget
Widget _buildConcertNotifications() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_concert_notifications".tr, style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 7.v), Text("lbl_push_email".tr, style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 13.v))]); } 
/// Section Widget
Widget _buildArtistUpdates() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_artist_updates".tr, style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 5.v), Text("lbl_push_email".tr, style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 11.v, bottom: 13.v))]); } 
/// Section Widget
Widget _buildProductNews() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_product_news".tr, style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 6.v), Text("lbl_email".tr, style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 13.v, bottom: 12.v))]); } 
/// Section Widget
Widget _buildHearMeOffers() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_hearme_offers".tr, style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 7.v), Text("lbl_push_email".tr, style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 13.v))]); } 
/// Section Widget
Widget _buildNewEpisodes() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_new_episodes".tr, style: CustomTextStyles.titleMediumSemiBold_1), SizedBox(height: 5.v), Text("lbl_push_email".tr, style: CustomTextStyles.titleSmallMedium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 11.v, bottom: 13.v))]); } 
 }
