import 'package:almohsen_s_application13/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_title.dart';import 'package:almohsen_s_application13/widgets/custom_radio_button.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application13/core/app_export.dart';import 'controller/language_controller.dart';class LanguageScreen extends GetWidget<LanguageController> {const LanguageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_suggested".tr, style: theme.textTheme.titleLarge), SizedBox(height: 22.v), _buildSuggestedRadioGroup(), SizedBox(height: 30.v), Divider(), SizedBox(height: 30.v), Text("lbl_others".tr, style: theme.textTheme.titleLarge), SizedBox(height: 23.v), _buildOthersRadioGroup(), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 53.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 14.v)), title: AppbarTitle(text: "lbl_language".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildSuggestedRadioGroup() { return Obx(() => Column(children: [CustomRadioButton(width: 380.h, text: "lbl_english_us".tr, value: controller.languageModelObj.value.radioList.value[0], groupValue: controller.suggestedRadioGroup.value, isRightCheck: true, onChange: (value) {controller.suggestedRadioGroup.value = value;}), Padding(padding: EdgeInsets.only(top: 20.v), child: CustomRadioButton(width: 380.h, text: "lbl_english_uk".tr, value: controller.languageModelObj.value.radioList.value[1], groupValue: controller.suggestedRadioGroup.value, isRightCheck: true, onChange: (value) {controller.suggestedRadioGroup.value = value;}))])); } 
/// Section Widget
Widget _buildOthersRadioGroup() { return Obx(() => Column(children: [CustomRadioButton(width: 380.h, text: "lbl_mandarin".tr, value: controller.languageModelObj.value.radioList1.value[0], groupValue: controller.othersRadioGroup.value, isRightCheck: true, onChange: (value) {controller.othersRadioGroup.value = value;}), Padding(padding: EdgeInsets.only(top: 20.v), child: CustomRadioButton(width: 380.h, text: "lbl_hindi".tr, value: controller.languageModelObj.value.radioList1.value[1], groupValue: controller.othersRadioGroup.value, isRightCheck: true, onChange: (value) {controller.othersRadioGroup.value = value;})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 380.h, text: "lbl_spanish".tr, value: controller.languageModelObj.value.radioList1.value[2], groupValue: controller.othersRadioGroup.value, isRightCheck: true, onChange: (value) {controller.othersRadioGroup.value = value;})), Padding(padding: EdgeInsets.only(top: 17.v), child: CustomRadioButton(width: 380.h, text: "lbl_french".tr, value: controller.languageModelObj.value.radioList1.value[3], groupValue: controller.othersRadioGroup.value, isRightCheck: true, onChange: (value) {controller.othersRadioGroup.value = value;})), Padding(padding: EdgeInsets.only(top: 20.v), child: CustomRadioButton(width: 380.h, text: "lbl_arabic".tr, value: controller.languageModelObj.value.radioList1.value[4], groupValue: controller.othersRadioGroup.value, isRightCheck: true, onChange: (value) {controller.othersRadioGroup.value = value;})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 380.h, text: "lbl_bengali".tr, value: controller.languageModelObj.value.radioList1.value[5], groupValue: controller.othersRadioGroup.value, isRightCheck: true, onChange: (value) {controller.othersRadioGroup.value = value;}))])); } 
 }
