import 'package:almohsen_s_application13/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_leading_circleimage.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_subtitle_one.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_subtitle.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_trailing_image.dart';import 'widgets/trendingnowframe_item_widget.dart';import 'models/trendingnowframe_item_model.dart';import 'widgets/artistsframe_item_widget.dart';import 'models/artistsframe_item_model.dart';import 'widgets/topchartslist_item_widget.dart';import 'models/topchartslist_item_model.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application13/core/app_export.dart';import 'controller/home_controller.dart';import 'models/home_model.dart';
// ignore_for_file: must_be_immutable
class HomePage extends StatelessWidget {HomePage({Key? key}) : super(key: key);

HomeController controller = Get.put(HomeController(HomeModel().obs));

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 27.v), child: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(popularArtistsText: "lbl_trending_now".tr, seeAllText: "lbl_see_all".tr, onTapSeeAllText: () {onTapTxtSeeAllText();})), SizedBox(height: 13.v), _buildTrendingNowFrame(), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(popularArtistsText: "lbl_popular_artists".tr, seeAllText: "lbl_see_all".tr, onTapSeeAllText: () {onTapTxtSeeAllText1();})), SizedBox(height: 13.v), _buildArtistsFrame(), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(popularArtistsText: "lbl_top_charts".tr, seeAllText: "lbl_see_all".tr)), SizedBox(height: 13.v), _buildTopChartsList()]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 53.v, leadingWidth: 72.h, leading: AppbarLeadingCircleimage(imagePath: ImageConstant.imgEllipse48x48, margin: EdgeInsets.only(left: 24.h, top: 2.v, bottom: 3.v)), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [AppbarSubtitleOne(text: "lbl_good_morning".tr, margin: EdgeInsets.only(right: 18.h)), SizedBox(height: 6.v), AppbarSubtitle(text: "lbl_andrew_ainsley".tr)])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 12.v, right: 13.h)), AppbarTrailingImage(imagePath: ImageConstant.imgIconsGray90001, margin: EdgeInsets.only(left: 20.h, top: 12.v, right: 37.h))]); } 
/// Section Widget
Widget _buildTrendingNowFrame() { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 220.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: controller.homeModelObj.value.trendingnowframeItemList.value.length, itemBuilder: (context, index) {TrendingnowframeItemModel model = controller.homeModelObj.value.trendingnowframeItemList.value[index]; return TrendingnowframeItemWidget(model);})))); } 
/// Section Widget
Widget _buildArtistsFrame() { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 193.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: controller.homeModelObj.value.artistsframeItemList.value.length, itemBuilder: (context, index) {ArtistsframeItemModel model = controller.homeModelObj.value.artistsframeItemList.value[index]; return ArtistsframeItemWidget(model);})))); } 
/// Section Widget
Widget _buildTopChartsList() { return Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: controller.homeModelObj.value.topchartslistItemList.value.length, itemBuilder: (context, index) {TopchartslistItemModel model = controller.homeModelObj.value.topchartslistItemList.value[index]; return TopchartslistItemWidget(model);})))); } 
/// Common widget
Widget _buildPopularArtistsRow({required String popularArtistsText, required String seeAllText, Function? onTapSeeAllText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text(popularArtistsText, style: theme.textTheme.headlineSmall!.copyWith(color: appTheme.gray90001)), GestureDetector(onTap: () {onTapSeeAllText!.call();}, child: Padding(padding: EdgeInsets.only(bottom: 7.v), child: Text(seeAllText, style: CustomTextStyles.titleMediumOnPrimaryContainer16.copyWith(color: theme.colorScheme.onPrimaryContainer))))]); } 
/// Navigates to the trendingNowScreen when the action is triggered.
onTapTxtSeeAllText() { Get.toNamed(AppRoutes.trendingNowScreen, ); } 
/// Navigates to the popularArtistsScreen when the action is triggered.
onTapTxtSeeAllText1() { Get.toNamed(AppRoutes.popularArtistsScreen, ); } 
 }
