import 'package:almohsen_s_application13/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_title.dart';import 'package:almohsen_s_application13/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application13/core/app_export.dart';import 'controller/forgot_password_controller.dart';class ForgotPasswordScreen extends GetWidget<ForgotPasswordController> {const ForgotPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 34.v), child: Column(children: [SizedBox(height: 18.v), CustomImageView(imagePath: ImageConstant.imgGroup321, height: 250.v, width: 276.h), SizedBox(height: 34.v), Container(width: 374.h, margin: EdgeInsets.only(right: 5.h), child: Text("msg_select_which_contact".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumMedium.copyWith(height: 1.40))), SizedBox(height: 21.v), _buildForgotPasswordRow1(), SizedBox(height: 24.v), _buildForgotPasswordRow2()])), bottomNavigationBar: _buildContinueButton())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "lbl_forgot_password".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildForgotPasswordRow1() { return Container(padding: EdgeInsets.all(21.h), decoration: AppDecoration.outlineOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Row(children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgUser, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 20.h, top: 16.v, bottom: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_via_sms".tr, style: CustomTextStyles.titleSmallGray600), SizedBox(height: 10.v), Text("lbl_1_111_99".tr, style: CustomTextStyles.titleMedium16)]))])); } 
/// Section Widget
Widget _buildForgotPasswordRow2() { return Container(padding: EdgeInsets.all(23.h), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Row(children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgCheckmarkOnprimarycontainer, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 20.h, top: 15.v, bottom: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_via_email".tr, style: CustomTextStyles.titleSmallGray600), SizedBox(height: 11.v), Text("lbl_user_domain_com".tr, style: CustomTextStyles.titleMedium16)]))])); } 
/// Section Widget
Widget _buildContinueButton() { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v), onPressed: () {onTapContinueButton();}); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
/// Navigates to the filledOtpScreen when the action is triggered.
onTapContinueButton() { Get.toNamed(AppRoutes.filledOtpScreen, ); } 
 }
