import 'package:almohsen_s_application13/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_title.dart';import 'package:almohsen_s_application13/widgets/custom_switch.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application13/core/app_export.dart';import 'controller/audio_video_controller.dart';class AudioVideoScreen extends GetWidget<AudioVideoController> {const AudioVideoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 33.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_audio_quality".tr, style: theme.textTheme.titleLarge), SizedBox(height: 32.v), _buildAudioQualityRow1(dynamicText: "lbl_wi_fi_streaming".tr, dynamicText1: "lbl_high".tr), SizedBox(height: 32.v), _buildAudioQualityRow1(dynamicText: "msg_data_cellular_streaming".tr, dynamicText1: "lbl_automatic".tr), SizedBox(height: 32.v), _buildAudioQualityRow4(), SizedBox(height: 32.v), _buildAudioQualityRow1(dynamicText: "lbl_download".tr, dynamicText1: "lbl_normal".tr), SizedBox(height: 34.v), _buildAudioQualityRow6(), SizedBox(height: 34.v), _buildAudioQualityRow7(), SizedBox(height: 33.v), Text("lbl_video_quality".tr, style: theme.textTheme.titleLarge), SizedBox(height: 32.v), _buildAudioQualityRow1(dynamicText: "lbl_wi_fi_streaming".tr, dynamicText1: "lbl_high".tr), SizedBox(height: 32.v), _buildAudioQualityRow1(dynamicText: "msg_data_cellular_streaming".tr, dynamicText1: "lbl_medium".tr), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 9.v)), title: AppbarTitle(text: "lbl_audio_video".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildAudioQualityRow4() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("msg_auto_adjust_quality".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Obx(() => CustomSwitch(value: controller.isSelectedSwitch.value, onChange: (value) {controller.isSelectedSwitch.value = value;}))]); } 
/// Section Widget
Widget _buildAudioQualityRow6() { return Row(children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("msg_download_only_using".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Obx(() => CustomSwitch(margin: EdgeInsets.only(left: 41.h), value: controller.isSelectedSwitch1.value, onChange: (value) {controller.isSelectedSwitch1.value = value;}))]); } 
/// Section Widget
Widget _buildAudioQualityRow7() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_equalizer".tr, style: CustomTextStyles.titleMediumSemiBold_1)), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 3.v))]); } 
/// Common widget
Widget _buildAudioQualityRow1({required String dynamicText, required String dynamicText1, }) { return Row(children: [Text(dynamicText, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray90001)), Spacer(), Text(dynamicText1, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray90001)), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 20.h, bottom: 3.v))]); } 
 }
