import 'package:almohsen_s_application13/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_title.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_trailing_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application13/core/app_export.dart';import 'controller/playlists_controller.dart';import 'package:almohsen_s_application13/presentation/new_playlist_bottomsheet/new_playlist_bottomsheet.dart';import 'package:almohsen_s_application13/presentation/new_playlist_bottomsheet/controller/new_playlist_controller.dart';class PlaylistsScreen extends GetWidget<PlaylistsController> {const PlaylistsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildSortByRow(), SizedBox(height: 22.v), Divider(), SizedBox(height: 23.v), GestureDetector(onTap: () {onTapTypeListThemeLight();}, child: Row(children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradientRedToOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgCategoriesPlus, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 16.h, top: 30.v, bottom: 27.v), child: Text("msg_add_new_playlist".tr, style: theme.textTheme.titleMedium))])), SizedBox(height: 24.v), _buildTypeListThemeLightRow(), SizedBox(height: 24.v), _buildMyFavoritePopRow(), SizedBox(height: 24.v), _buildLoremIpsumRow(), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 53.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 14.v)), title: AppbarTitle(text: "lbl_playlists".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 11.v, right: 14.h)), AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.only(left: 20.h, top: 11.v, right: 38.h))]); } 
/// Section Widget
Widget _buildSortByRow() { return Row(children: [Text("lbl_sort_by".tr, style: theme.textTheme.titleLarge), Spacer(), Text("lbl_recently_added".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer16), CustomImageView(imagePath: ImageConstant.imgIconlyCurvedSwap, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 12.h, bottom: 4.v))]); } 
/// Section Widget
Widget _buildTypeListThemeLightRow() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 177.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 80.adaptSize, width: 80.adaptSize, padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradientRedToOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: CustomImageView(imagePath: ImageConstant.imgFavoriteWhiteA700, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.symmetric(vertical: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_your_likes".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), Text("lbl_270_songs".tr, style: theme.textTheme.labelLarge)]))])), CustomImageView(imagePath: ImageConstant.imgCategoriesMore, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 30.v))]); } 
/// Section Widget
Widget _buildMyFavoritePopRow() { return GestureDetector(onTap: () {onTapMyFavoritePopRow();}, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgImage84, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(20.h)), Expanded(child: Padding(padding: EdgeInsets.only(left: 16.h, top: 19.v, bottom: 16.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_my_favorite_pop".tr, style: theme.textTheme.titleMedium), SizedBox(height: 6.v), Text("lbl_345_songs".tr, style: theme.textTheme.labelLarge)]), CustomImageView(imagePath: ImageConstant.imgCategoriesMore, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 10.v, bottom: 13.v))])))])); } 
/// Section Widget
Widget _buildLoremIpsumRow() { return GestureDetector(onTap: () {onTapLoremIpsumRow();}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 204.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgImage85, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(20.h)), Padding(padding: EdgeInsets.only(top: 19.v, bottom: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_90s_old_song".tr, style: theme.textTheme.titleMedium), SizedBox(height: 7.v), Text("lbl_127_songs".tr, style: theme.textTheme.labelLarge)]))])), CustomImageView(imagePath: ImageConstant.imgCategoriesMore, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 30.v))])); } 

/// Displays a scrollable bottom sheet widget using the [Get] package 
/// and the [NewPlaylistBottomsheet] widget.
///
/// The bottom sheet is controlled by the [NewPlaylistController]
/// and is displayed using the [Get.bottomSheet] method with
/// [isScrollControlled] set to true.

onTapTypeListThemeLight() { Get.bottomSheet(NewPlaylistBottomsheet(Get.put(NewPlaylistController(),),),isScrollControlled: true,); } 
/// Navigates to the playlistDetailsScreen when the action is triggered.
onTapMyFavoritePopRow() { Get.toNamed(AppRoutes.playlistDetailsScreen, ); } 
/// Navigates to the playlistDetailsScreen when the action is triggered.
onTapLoremIpsumRow() { Get.toNamed(AppRoutes.playlistDetailsScreen, ); } 
 }
