import 'package:almohsen_s_application13/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_leading_image.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application13/core/app_export.dart';import 'controller/subscribe_controller.dart';class SubscribeScreen extends GetWidget<SubscribeController> {const SubscribeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(children: [Text("msg_subscribe_to_premium".tr, style: CustomTextStyles.headlineLargeOnPrimaryContainer), SizedBox(height: 13.v), Container(width: 362.h, margin: EdgeInsets.only(left: 9.h, right: 8.h), child: Text("msg_enjoy_listening2".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumPrimaryMedium16.copyWith(height: 1.40))), SizedBox(height: 21.v), _buildPremiumSection(), SizedBox(height: 24.v), _buildPremiumSection2(), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOutlineArrow, margin: EdgeInsets.fromLTRB(24.h, 11.v, 376.h, 11.v))); } 
/// Section Widget
Widget _buildPremiumSection() { return GestureDetector(onTap: () {onTapPremiumSection();}, child: Container(padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradientOrangeAToOrangeA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 7.v), CustomImageView(imagePath: ImageConstant.imgUserWhiteA700, height: 44.v, width: 50.h, alignment: Alignment.center), SizedBox(height: 23.v), Align(alignment: Alignment.center, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_9_99".tr, style: CustomTextStyles.headlineLargeWhiteA700), Padding(padding: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 8.v), child: Text("lbl_month".tr, style: CustomTextStyles.titleMediumGray100))])), SizedBox(height: 15.v), Divider(), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(right: 27.h), child: _buildPremiumSection3(text: "msg_listening_with_better".tr)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 22.h), child: _buildPremiumSection4(listeningText: "msg_listening_without".tr)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 25.h), child: _buildPremiumSection5(shufflePlayText: "msg_shuffle_play_download".tr))]))); } 
/// Section Widget
Widget _buildPremiumSection2() { return Container(padding: EdgeInsets.all(24.h), decoration: AppDecoration.gradientPurpleAToDeepPurpleA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 7.v), CustomImageView(imagePath: ImageConstant.imgUserWhiteA700, height: 44.v, width: 50.h, alignment: Alignment.center), SizedBox(height: 23.v), Align(alignment: Alignment.center, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_19_99".tr, style: CustomTextStyles.headlineLargeWhiteA700), Padding(padding: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 8.v), child: Text("lbl_3_months".tr, style: CustomTextStyles.titleMediumGray100))])), SizedBox(height: 15.v), Divider(), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(right: 27.h), child: _buildPremiumSection3(text: "msg_listening_with_better".tr)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 22.h), child: _buildPremiumSection4(listeningText: "msg_listening_without".tr)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 25.h), child: _buildPremiumSection5(shufflePlayText: "msg_shuffle_play_download".tr))])); } 
/// Common widget
Widget _buildPremiumSection3({required String text}) { return Row(children: [CustomImageView(imagePath: ImageConstant.imgCategoriesCheck, height: 32.adaptSize, width: 32.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 8.v, bottom: 4.v), child: Text(text, style: CustomTextStyles.titleMediumWhiteA700Medium.copyWith(color: appTheme.whiteA700)))]); } 
/// Common widget
Widget _buildPremiumSection4({required String listeningText}) { return Row(children: [CustomImageView(imagePath: ImageConstant.imgCategoriesCheck, height: 32.adaptSize, width: 32.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 8.v, bottom: 4.v), child: Text(listeningText, style: CustomTextStyles.titleMediumWhiteA700Medium.copyWith(color: appTheme.whiteA700)))]); } 
/// Common widget
Widget _buildPremiumSection5({required String shufflePlayText}) { return Row(children: [CustomImageView(imagePath: ImageConstant.imgCategoriesCheck, height: 32.adaptSize, width: 32.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 7.v, bottom: 4.v), child: Text(shufflePlayText, style: CustomTextStyles.titleMediumWhiteA700Medium.copyWith(color: appTheme.whiteA700)))]); } 
/// Navigates to the paymentMethodScreen when the action is triggered.
onTapPremiumSection() { Get.toNamed(AppRoutes.paymentMethodScreen, ); } 
 }
