import 'package:almohsen_s_application13/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_title.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_trailing_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'widgets/popularpodcastslist_item_widget.dart';import 'models/popularpodcastslist_item_model.dart';import 'widgets/artistslist_item_widget.dart';import 'models/artistslist_item_model.dart';import 'widgets/explorepodcastsgrid_item_widget.dart';import 'models/explorepodcastsgrid_item_model.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application13/core/app_export.dart';import 'controller/podcasts_controller.dart';class PodcastsScreen extends GetWidget<PodcastsController> {const PodcastsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 32.v), child: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(popularArtistsText: "msg_popular_podcasts".tr, seeAllText: "lbl_see_all".tr)), SizedBox(height: 13.v), _buildPopularPodcastsList(), SizedBox(height: 30.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(popularArtistsText: "lbl_popular_artists".tr, seeAllText: "lbl_see_all".tr)), SizedBox(height: 13.v), _buildArtistsList(), SizedBox(height: 30.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(popularArtistsText: "lbl_categories".tr, seeAllText: "lbl_see_all".tr)), SizedBox(height: 13.v), _buildExplorePodcastsGrid()]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "lbl_podcasts".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 10.v, right: 10.h)), AppbarTrailingImage(imagePath: ImageConstant.imgTelevision, margin: EdgeInsets.only(left: 20.h, top: 10.v, right: 10.h)), AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.only(left: 20.h, top: 10.v, right: 34.h))]); } 
/// Section Widget
Widget _buildPopularPodcastsList() { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 220.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: controller.podcastsModelObj.value.popularpodcastslistItemList.value.length, itemBuilder: (context, index) {PopularpodcastslistItemModel model = controller.podcastsModelObj.value.popularpodcastslistItemList.value[index]; return PopularpodcastslistItemWidget(model);})))); } 
/// Section Widget
Widget _buildArtistsList() { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 209.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: controller.podcastsModelObj.value.artistslistItemList.value.length, itemBuilder: (context, index) {ArtistslistItemModel model = controller.podcastsModelObj.value.artistslistItemList.value[index]; return ArtistslistItemWidget(model);})))); } 
/// Section Widget
Widget _buildExplorePodcastsGrid() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Obx(() => GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 121.v, crossAxisCount: 2, mainAxisSpacing: 12.h, crossAxisSpacing: 12.h), physics: NeverScrollableScrollPhysics(), itemCount: controller.podcastsModelObj.value.explorepodcastsgridItemList.value.length, itemBuilder: (context, index) {ExplorepodcastsgridItemModel model = controller.podcastsModelObj.value.explorepodcastsgridItemList.value[index]; return ExplorepodcastsgridItemWidget(model, onTapExploreCard: () {onTapExploreCard();});}))); } 
/// Common widget
Widget _buildPopularArtistsRow({required String popularArtistsText, required String seeAllText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(popularArtistsText, style: theme.textTheme.headlineSmall!.copyWith(color: appTheme.gray90001))), Padding(padding: EdgeInsets.only(bottom: 10.v), child: Text(seeAllText, style: CustomTextStyles.titleMediumOnPrimaryContainer16.copyWith(color: theme.colorScheme.onPrimaryContainer)))]); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
/// Navigates to the newReleasesScreen when the action is triggered.
onTapExploreCard() { Get.toNamed(AppRoutes.newReleasesScreen, ); } 
 }
