import 'package:almohsen_s_application13/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_title.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_trailing_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'widgets/podcastlist_item_widget.dart';import 'models/podcastlist_item_model.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application13/core/app_export.dart';import 'controller/my_library_controller.dart';import 'models/my_library_model.dart';
// ignore_for_file: must_be_immutable
class MyLibraryPage extends StatelessWidget {MyLibraryPage({Key? key}) : super(key: key);

MyLibraryController controller = Get.put(MyLibraryController(MyLibraryModel().obs));

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 30.v), child: Column(children: [_buildAutoLayoutHorizontal(), SizedBox(height: 12.v), _buildPodcastList(), SizedBox(height: 29.v), Divider(indent: 24.h, endIndent: 24.h), SizedBox(height: 29.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildSongs(categoriesImage: ImageConstant.imgDownload, songText: "lbl_playlists".tr, onTapSongs: () {onTapSongs();})), SizedBox(height: 29.v), _buildDownloads(), SizedBox(height: 32.v), _buildPodcasts(), SizedBox(height: 32.v), _buildAlbums(), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildSongs(categoriesImage: ImageConstant.imgCategoriesMusic, songText: "lbl_songs".tr)), SizedBox(height: 29.v), _buildArtists(), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 51.v, leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgVector, margin: EdgeInsets.only(left: 24.h, top: 9.v, bottom: 10.v)), title: AppbarTitle(text: "lbl_my_library".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 11.v, right: 12.h)), AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.only(left: 20.h, top: 11.v, right: 36.h))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_your_history".tr, style: theme.textTheme.headlineSmall)), Padding(padding: EdgeInsets.only(bottom: 10.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer16))])); } 
/// Section Widget
Widget _buildPodcastList() { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 193.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: controller.myLibraryModelObj.value.podcastlistItemList.value.length, itemBuilder: (context, index) {PodcastlistItemModel model = controller.myLibraryModelObj.value.podcastlistItemList.value[index]; return PodcastlistItemWidget(model);})))); } 
/// Section Widget
Widget _buildDownloads() { return GestureDetector(onTap: () {onTapDownloads();}, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedArrow, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_downloads".tr, style: theme.textTheme.headlineSmall))]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]))); } 
/// Section Widget
Widget _buildPodcasts() { return GestureDetector(onTap: () {onTapPodcasts();}, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 145.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgCategoriesPodcast, height: 28.adaptSize, width: 28.adaptSize), Text("lbl_podcasts".tr, style: theme.textTheme.headlineSmall)])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))]))); } 
/// Section Widget
Widget _buildAlbums() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 132.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedPlay, height: 28.adaptSize, width: 28.adaptSize), Text("lbl_albums".tr, style: theme.textTheme.headlineSmall)])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildArtists() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 120.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurved3, height: 28.adaptSize, width: 28.adaptSize), Text("lbl_artists".tr, style: theme.textTheme.headlineSmall)])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Common widget
Widget _buildSongs({required String categoriesImage, required String songText, Function? onTapSongs, }) { return GestureDetector(onTap: () {onTapSongs!.call();}, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: categoriesImage, height: 28.adaptSize, width: 28.adaptSize, margin: EdgeInsets.only(bottom: 3.v)), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v), child: Text(songText, style: theme.textTheme.headlineSmall!.copyWith(color: appTheme.gray90001))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 4.v, bottom: 7.v))])); } 
/// Navigates to the playlistsScreen when the action is triggered.
onTapSongs() { Get.toNamed(AppRoutes.playlistsScreen, ); } 
/// Navigates to the downloadsScreen when the action is triggered.
onTapDownloads() { Get.toNamed(AppRoutes.downloadsScreen, ); } 
/// Navigates to the yourLikesTabContainerScreen when the action is triggered.
onTapPodcasts() { Get.toNamed(AppRoutes.yourLikesTabContainerScreen, ); } 
 }
