import 'package:almohsen_s_application13/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_title.dart';import 'package:almohsen_s_application13/widgets/app_bar/appbar_trailing_image.dart';import 'widgets/newreleaseslist_item_widget.dart';import 'models/newreleaseslist_item_model.dart';import 'widgets/newreleasesgrid_item_widget.dart';import 'models/newreleasesgrid_item_model.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application13/core/app_export.dart';import 'controller/new_releases_controller.dart';class NewReleasesScreen extends GetWidget<NewReleasesController> {const NewReleasesScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 31.v), child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_the_best_new_releases".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 16.v), _buildNewReleasesList(), SizedBox(height: 36.v), Text("msg_new_albums_single".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 13.v), _buildNewReleasesGrid()])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 9.v), onTap: () {onTapArrowDown();}), title: AppbarTitle(text: "lbl_new_releases".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 9.v))]); } 
/// Section Widget
Widget _buildNewReleasesList() { return SizedBox(height: 242.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: controller.newReleasesModelObj.value.newreleaseslistItemList.value.length, itemBuilder: (context, index) {NewreleaseslistItemModel model = controller.newReleasesModelObj.value.newreleaseslistItemList.value[index]; return NewreleaseslistItemWidget(model);}))); } 
/// Section Widget
Widget _buildNewReleasesGrid() { return Obx(() => GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 245.v, crossAxisCount: 2, mainAxisSpacing: 12.h, crossAxisSpacing: 12.h), physics: NeverScrollableScrollPhysics(), itemCount: controller.newReleasesModelObj.value.newreleasesgridItemList.value.length, itemBuilder: (context, index) {NewreleasesgridItemModel model = controller.newReleasesModelObj.value.newreleasesgridItemList.value[index]; return NewreleasesgridItemWidget(model);})); } 

/// Navigates to the previous screen.
onTapArrowDown() { Get.back(); } 
 }
